### ISSUE TITLE
traefik letsencrypt http challenge

### ISSUE THREAD

**Issue by cfoellmann** [DannyBen/redirectly#12]
Hi,

me again :-)

I am thankful for your great image and your help with the proper config.

I run traefik and use the http challenge for letsencrypt:
my docker compose.yml
```yml
# Redirect Server
# https://github.com/dannyben/redirectly
#

networks:
  proxy:
    external: true

services:
  redirectly:
    image: dannyben/redirectly
    container_name: redirectly
    ports:
      - 3000:3000
    volumes:
      - /var/lib/docker/compose/redirectly/redirects.ini:/app/redirects.ini
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redirectly.entrypoints=https"
      - "traefik.http.routers.redirectly.rule=(Host(`domain.de`,`www.domain.de`,`aliasforthird.de`,`www.aliasforthird.de`))"
      - "traefik.http.routers.redirectly.tls=true"
      - "traefik.http.routers.redirectly.tls.certresolver=http"
      - "traefik.http.routers.redirectly.service=redirectly"
      - "traefik.http.services.redirectly.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.redirectly.middlewares=default@file"
    networks:
      proxy:
    restart: unless-stopped
```

redirects.ini
```ini
(*)domain.de = https://anotherpage.com/sub/folder/
(*)aliasforthird.de/*rest = https://third.com/%{rest}
```

Since I need SSL for all domains mapped to redirectly I need traefik to be able to do the HTTP challenge.
Any idea how?

I
